### ISSUE TITLE
some small questions

### ISSUE THREAD

**Issue by yhelpq** [leaderj1001/Action-Localization#4]
(1) Do I need to use "make_tubelet" files in "action-baseline" and "action-transformer" ?
(2) Where are the files used in "action-baseline" and "action-transformer" projects obtained? For example "ori_action_list.pkl", "fps_dict.pkl", and "Main/train.txt"?

**Comment by wanna-fly** [comment]
So what's the solution?Do we need to generate these files by ourselves?
